#!/usr/bin/env bash
# apply.sh — vendor openvm + stark-backend at the revs openvm-eth pins, apply the
# multi-GPU patch (docs/openvm-multigpu.md, Edits 1-4) FULLY AUTOMATICALLY, and wire
# auto-discovered cargo [patch] overrides.
#
#   ./apply.sh <path-to-openvm-eth>
#
# All four edits are applied by exact-string match against the source. Each prints
# OK / SKIP (already applied) / FAIL (string moved -> hand-apply from the doc). The
# [patch] section is generated by reading Cargo.lock (every crate from each git source
# is redirected to its vendored dir, so there is no possible type-duplication).
#
# DESIGN FOR CHEAP ITERATION: the CUDA code is all #[cfg(feature="cuda")], so you can
# shake out 90% of compile errors WITHOUT a GPU box — see ../docs/openvm-multigpu.md
# "compile-check for free". Only the final cuda build + the run need the box.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ETH="${1:?usage: ./apply.sh <path-to-openvm-eth>}"
ETH="$(cd "$ETH" && pwd)"
VENDOR="${VENDOR:-$ETH/.vendor}"
mkdir -p "$VENDOR"
TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT
FAILED=0

LOCK="$ETH/Cargo.lock"
[[ -f "$LOCK" ]] || { echo "ERROR: $LOCK not found. Run 'cargo generate-lockfile' in $ETH first." >&2; exit 1; }

# A PRIOR build churns Cargo.lock: cargo [patch] rewrites the openvm/stark crates to path sources,
# dropping their "git+…#<rev>" lines — after which rev_for below finds nothing. Restore the committed
# lock first (HEAD is the pinned rev) so re-runs are idempotent.
if git -C "$ETH" rev-parse --git-dir >/dev/null 2>&1; then
  git -C "$ETH" checkout -- Cargo.lock 2>/dev/null && echo "restored committed Cargo.lock (for rev extraction)" || true
fi

# ── extract pinned revs from Cargo.lock ──────────────────────────────────────
rev_for() { grep -oE "source = \"git\+[^\"]*$1[^\"]*#[0-9a-f]{40}\"" "$LOCK" | head -n1 | grep -oE '[0-9a-f]{40}'; }
OPENVM_REV="$(rev_for 'openvm-org/openvm.git')"
STARK_REV="$(rev_for 'openvm-org/stark-backend.git')"
echo "pinned openvm rev        : ${OPENVM_REV:-<none>}"
echo "pinned stark-backend rev : ${STARK_REV:-<none>}"
[[ -n "$OPENVM_REV" && -n "$STARK_REV" ]] || { echo "ERROR: could not read pinned revs from Cargo.lock" >&2; exit 1; }

clone_at() {  # url dir rev
  [[ -d "$2/.git" ]] || git clone "$1" "$2"
  git -C "$2" fetch --depth 1 origin "$3" 2>/dev/null || git -C "$2" fetch origin
  git -C "$2" checkout -q "$3"
}
echo "== vendoring =="
clone_at "https://github.com/openvm-org/openvm.git"        "$VENDOR/openvm"        "$OPENVM_REV"
clone_at "https://github.com/openvm-org/stark-backend.git" "$VENDOR/stark-backend" "$STARK_REV"
{ echo "applied : $(date -u)"; echo "openvm  : $OPENVM_REV"; echo "stark   : $STARK_REV"; } > "$HERE/applied-revs.txt"

# ── RESET patched files to pristine, THEN re-apply everything from scratch ────
# Marker-based SKIP assumes "marker present == edit fully applied". Across apply.sh versions /
# partial prior runs that can be false (e.g. the enum variant applied but the match arm missing ->
# runtime `unreachable!()`). Resetting the tracked files first makes every run deterministic: the
# edits below always apply from a clean slate. Cheap (git checkout, no re-clone; untracked .vendor,
# target/, guest ELF are left intact).
echo "== reset patched files to pristine (deterministic re-apply) =="
git -C "$ETH" checkout -- . 2>/dev/null && echo "  reset openvm-eth" || true
git -C "$VENDOR/openvm" checkout -- . 2>/dev/null && echo "  reset .vendor/openvm" || true
git -C "$VENDOR/stark-backend" checkout -- . 2>/dev/null && echo "  reset .vendor/stark-backend" || true

# ── python edit helpers (exact-string; status per edit) ──────────────────────
py() { python3 - "$@"; }
edit_replace() {  # file  old-file  new-file  marker
  py "$1" "$2" "$3" "$4" <<'PY'
import sys
f,oldf,newf,marker=sys.argv[1:5]
try: src=open(f,encoding='utf-8').read()
except Exception as e: print(f"  FAIL: cannot read {f}: {e}"); sys.exit(3)
if marker in src: print(f"  SKIP (already applied): {f}"); sys.exit(0)
old=open(oldf,encoding='utf-8').read(); new=open(newf,encoding='utf-8').read()
if old not in src:
    print(f"  FAIL: target string not found in {f} (rev drift -> hand-apply from doc)"); sys.exit(3)
open(f,"w",encoding='utf-8').write(src.replace(old,new,1)); print(f"  OK: {f}")
PY
}
edit_append() {  # file  block-file  marker
  py "$1" "$2" "$3" <<'PY'
import sys
f,blockf,marker=sys.argv[1:4]
try: src=open(f,encoding='utf-8').read()
except Exception as e: print(f"  FAIL: cannot read {f}: {e}"); sys.exit(3)
if marker in src: print(f"  SKIP (already applied): {f}"); sys.exit(0)
open(f,"a",encoding='utf-8').write("\n"+open(blockf,encoding='utf-8').read()); print(f"  OK (appended): {f}")
PY
}
run() { "$@"; [[ $? -eq 3 ]] && FAILED=1; }

SDK="$VENDOR/openvm/crates/sdk/src"
CCOMMON="$VENDOR/stark-backend/crates/cuda-common/src/common.rs"
RB="$ETH/bin/reth-benchmark"
RBLIB="$RB/src/lib.rs"

# ── Edit 1: set_device_ordinal in cuda-common (append) ───────────────────────
echo "== Edit 1: cuda-common set_device_ordinal =="
cat > "$TMP/e1.rs" <<'RS'
/// Pin the CURRENT host thread to CUDA device `ordinal` and eagerly create its context.
/// Multi-GPU fan-out: each segment-proving thread calls this before allocating, so all of
/// its proof work lands on GPU `ordinal`.
pub fn set_device_ordinal(ordinal: i32) -> Result<(), CudaError> {
    unsafe {
        check(cudaSetDevice(ordinal))?;
        check(cudaFree(std::ptr::null_mut()))?;
    }
    Ok(())
}
RS
run edit_append "$CCOMMON" "$TMP/e1.rs" "set_device_ordinal"

# ── Edit 2a: device count before the segment loop ────────────────────────────
echo "== Edit 2a: AsyncAppProver num_gpus =="
printf '%s' '            let mut num_ins_last = 0;' > "$TMP/e2a_old.txt"
cat > "$TMP/e2a_new.txt" <<'RS'
            let mut num_ins_last = 0;
            // [multi-gpu] number of GPUs to fan segment proofs across (1 = stock path).
            let num_gpus: i32 = std::env::var("OPENVM_NUM_GPUS")
                .ok().and_then(|s| s.parse().ok()).filter(|&n| n >= 1).unwrap_or(1);
            #[cfg(not(feature = "cuda"))]
            let _ = num_gpus;
RS
run edit_replace "$SDK/prover/app.rs" "$TMP/e2a_old.txt" "$TMP/e2a_new.txt" "multi-gpu] number of GPUs"

# ── Edit 2b: pin the blocking thread to a GPU before building the local prover ─
echo "== Edit 2b: AsyncAppProver device pin =="
printf '%s' '                                    let mut worker = async_worker.local()?;' > "$TMP/e2b_old.txt"
cat > "$TMP/e2b_new.txt" <<'RS'
                                    // [multi-gpu] pin THIS blocking thread to a GPU ordinal
                                    // before any device allocation in local(). Direct cudart FFI:
                                    // openvm-sdk doesn't depend on openvm-cuda-common, but the cuda
                                    // build links cudart (via openvm-cuda-backend) so these symbols
                                    // resolve at final link.
                                    #[cfg(feature = "cuda")]
                                    {
                                        extern "C" {
                                            fn cudaSetDevice(device: i32) -> i32;
                                            fn cudaFree(ptr: *mut core::ffi::c_void) -> i32;
                                        }
                                        let __dev = (seg_idx as i32) % num_gpus;
                                        let __rc = unsafe { cudaSetDevice(__dev) };
                                        assert_eq!(__rc, 0, "cudaSetDevice failed: {__rc}");
                                        unsafe { cudaFree(core::ptr::null_mut()); }
                                    }
                                    let mut worker = async_worker.local()?;
RS
run edit_replace "$SDK/prover/app.rs" "$TMP/e2b_old.txt" "$TMP/e2b_new.txt" "multi-gpu] pin THIS blocking thread"

# ── Edit 3: Sdk::async_app_prover ────────────────────────────────────────────
echo "== Edit 3: Sdk::async_app_prover =="
printf '%s' '    // ======================== Keygen Related Methods ========================' > "$TMP/e3_old.txt"
cat > "$TMP/e3_new.txt" <<'RS'
    /// Multi-GPU app prover: fans continuation-segment proofs across `max_concurrency`
    /// blocking tasks, each pinned to a GPU ordinal (see AsyncAppProver::prove). Pair the
    /// result with `prover(exe)?.agg_prover` to aggregate into a single STARK.
    #[cfg(feature = "async")]
    pub fn async_app_prover(
        &self,
        exe: impl Into<ExecutableFormat>,
        max_concurrency: usize,
    ) -> Result<crate::prover::AsyncAppProver<E, VB>, SdkError>
    where
        E: 'static,
        VB: Clone + Send + Sync + 'static,
        VB::VmConfig: Send + Sync,
    {
        let exe = self.convert_to_exe(exe)?;
        let app_pk = self.app_pk();
        let prover = crate::prover::AsyncAppProver::<E, VB>::new(
            self.app_vm_builder.clone(),
            app_pk.app_vm_pk.clone(), // app_vm_pk is already Arc<VmProvingKey>
            exe,
            app_pk.leaf_verifier_program_commit(),
            max_concurrency,
        )?;
        Ok(prover)
    }

    // ======================== Keygen Related Methods ========================
RS
run edit_replace "$SDK/lib.rs" "$TMP/e3_old.txt" "$TMP/e3_new.txt" "pub fn async_app_prover"

# ── Edit 4a: reth-benchmark Cargo.toml — enable openvm-sdk/async ALWAYS ───────
# Not a reth-benchmark feature: turn async on at the openvm-sdk DEPENDENCY so the
# multi-GPU code path compiles with a plain `cargo build` (no cuda) -> free GPU-less
# compile-check. The cuda feature is left untouched (adds cuda on top of async).
echo "== Edit 4a: reth-benchmark openvm-sdk -> features=[\"async\"] =="
printf '%s' 'openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", branch = "main", default-features = false }' > "$TMP/e4a_old.txt"
printf '%s' 'openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", branch = "main", default-features = false, features = ["async"] }' > "$TMP/e4a_new.txt"
run edit_replace "$RB/Cargo.toml" "$TMP/e4a_old.txt" "$TMP/e4a_new.txt" 'default-features = false, features = ["async"]'

# ── Edit 4b: --num-gpus flag on HostArgs ─────────────────────────────────────
echo "== Edit 4b: HostArgs --num-gpus =="
printf '%s' '    #[arg(long, default_value_t = false)]
    pub skip_comparison: bool,' > "$TMP/e4b_old.txt"
cat > "$TMP/e4b_new.txt" <<'RS'
    #[arg(long, default_value_t = false)]
    pub skip_comparison: bool,

    /// Number of GPUs ONE process fans segment proofs across (1 = stock single-GPU path).
    #[arg(long, env = "OPENVM_NUM_GPUS", default_value_t = 1)]
    pub num_gpus: usize,
RS
run edit_replace "$RBLIB" "$TMP/e4b_old.txt" "$TMP/e4b_new.txt" "pub num_gpus: usize"

# ── Edit 4c: multi-GPU branch in the ProveStark arm ──────────────────────────
echo "== Edit 4c: ProveStark multi-GPU branch =="
printf '%s' '                        let mut prover = sdk.prover(elf)?.with_program_name(program_name);
                        let proof = prover.prove(stdin)?;' > "$TMP/e4c_old.txt"
cat > "$TMP/e4c_new.txt" <<'RS'
                        let proof = if args.num_gpus > 1 {
                            // [multi-gpu] fan app-segment proofs across GPUs, then aggregate.
                            unsafe { std::env::set_var("OPENVM_NUM_GPUS", args.num_gpus.to_string()); }
                            let async_prover = sdk.async_app_prover(elf.clone(), args.num_gpus)?;
                            let app_proof = tokio::task::block_in_place(|| {
                                tokio::runtime::Handle::current()
                                    .block_on(async_prover.prove(stdin))
                            })?;
                            let mut agg = sdk.prover(elf)?;
                            let leaf = agg.agg_prover.generate_leaf_proofs(&app_proof)?;
                            agg.agg_prover.aggregate_leaf_proofs(
                                leaf,
                                app_proof.user_public_values.public_values,
                            )?
                        } else {
                            let mut prover =
                                sdk.prover(elf)?.with_program_name(program_name);
                            prover.prove(stdin)?
                        };
RS
run edit_replace "$RBLIB" "$TMP/e4c_old.txt" "$TMP/e4c_new.txt" "multi-gpu] fan app-segment proofs"

# ══════════════ PATH ① — multi-process multi-GPU (the working multi-GPU path) ══════════════
# ② (in-process, above) crashes at runtime (VPMM cudaErrorInvalidResourceHandle). Path ① runs one
# GPU per PROCESS (CUDA_VISIBLE_DEVICES) so there's no cross-device resource sharing. These edits
# add: AppProver/AsyncAppProver::prove_shard (prove seg_idx%%N==worker_id) + reth-benchmark
# prove-segments/aggregate modes. Orchestrated by cluster/submit.sh.

echo "== Edit 5: AsyncAppProver::prove_shard (sdk app.rs) =="
printf '%s' '            Ok(cont_proof)
        }
    }
}' > "$TMP/e5_old.txt"
cat > "$TMP/e5_new.txt" <<'RS'
            Ok(cont_proof)
        }

        /// [multi-gpu path ①] Prove ONLY the continuation segments assigned to this worker
        /// (`seg_idx % num_workers == worker_id`), sequentially, on the single visible GPU
        /// (run each worker process with a distinct CUDA_VISIBLE_DEVICES). Pure execution
        /// advances the state through ALL segments (cheap, CPU); only assigned segments are
        /// proven (GPU). Returns the (index, proof) pairs plus the user-public-values proof IF
        /// this worker proved the terminal segment. The union of all workers is aggregated
        /// separately (reconstruct ContinuationVmProof -> AggStarkProver).
        pub fn prove_shard(
            &self,
            input: StdIn<Val<E::SC>>,
            worker_id: usize,
            num_workers: usize,
        ) -> eyre::Result<(
            Vec<(usize, openvm_stark_backend::proof::Proof<E::SC>)>,
            Option<UserPublicValuesProof<CHUNK, Val<E::SC>>>,
        )>
        where
            <VB::VmConfig as VmExecutionConfig<Val<E::SC>>>::Executor: Executor<Val<E::SC>>
                + MeteredExecutor<Val<E::SC>>
                + PreflightExecutor<Val<E::SC>, VB::RecordArena>,
        {
            assert!(self.vm_config().as_ref().continuation_enabled);
            check_max_constraint_degrees(self.vm_config().as_ref(), &self.fri_params());
            let mut pure = self.local()?;
            pure.instance.reset_state(input.clone());
            let mut state = pure.instance.state_mut().take().unwrap();
            let metered_ctx = pure.instance.vm.build_metered_ctx(&self.app_exe);
            let metered_interpreter = pure.instance.vm.metered_interpreter(&self.app_exe)?;
            let (segments, _) = metered_interpreter.execute_metered(input, metered_ctx)?;
            drop(metered_interpreter);
            let pure_interpreter = pure.instance.vm.interpreter(&self.app_exe)?;
            let mut out: Vec<(usize, openvm_stark_backend::proof::Proof<E::SC>)> = Vec::new();
            let mut user_pv: Option<UserPublicValuesProof<CHUNK, Val<E::SC>>> = None;
            let mut num_ins_last = 0;
            for (seg_idx, segment) in segments.into_iter().enumerate() {
                state = pure_interpreter.execute_from_state(state, Some(num_ins_last))?;
                num_ins_last = segment.num_insns;
                if seg_idx % num_workers != worker_id {
                    continue;
                }
                let start_state = state.clone();
                let mut worker = self.local()?;
                let instance = &mut worker.instance;
                let vm = &mut instance.vm;
                let preflight_interpreter = &mut instance.interpreter;
                let (segment_proof, final_memory) = vm.prove(
                    preflight_interpreter,
                    start_state,
                    Some(segment.num_insns),
                    &segment.trace_heights,
                )?;
                if let Some(final_memory) = final_memory {
                    let top_tree = vm.memory_top_tree().unwrap();
                    user_pv = Some(UserPublicValuesProof::compute(
                        vm.config().as_ref().memory_config.memory_dimensions(),
                        vm.config().as_ref().num_public_values,
                        &vm_poseidon2_hasher(),
                        &final_memory.memory,
                        top_tree,
                    ));
                }
                out.push((seg_idx, segment_proof));
            }
            Ok((out, user_pv))
        }
    }
}
RS
run edit_replace "$SDK/prover/app.rs" "$TMP/e5_old.txt" "$TMP/e5_new.txt" "pub fn prove_shard"

echo "== Edit 6: reth-benchmark prove-segments/aggregate modes =="
printf '%s' '    fs::read_object_from_file,' > "$TMP/e6a_old.txt"
printf '%s' '    fs::{read_object_from_file, write_object_to_file},' > "$TMP/e6a_new.txt"
run edit_replace "$RBLIB" "$TMP/e6a_old.txt" "$TMP/e6a_new.txt" "write_object_to_file"
printf '%s' '    DefaultStarkEngine, Sdk, StdIn,
};' > "$TMP/e6b_old.txt"
printf '%s' '    DefaultStarkEngine, Sdk, StdIn, SC,
};' > "$TMP/e6b_new.txt"
run edit_replace "$RBLIB" "$TMP/e6b_old.txt" "$TMP/e6b_new.txt" "StdIn, SC,"
printf '%s' '    /// Generate a full end-to-end STARK proof with aggregation.
    ProveStark,' > "$TMP/e6c_old.txt"
cat > "$TMP/e6c_new.txt" <<'RS'
    /// Generate a full end-to-end STARK proof with aggregation.
    ProveStark,
    /// [multi-gpu ①] Prove only THIS worker's shard of continuation segments (one GPU/process).
    ProveSegments,
    /// [multi-gpu ①] Aggregate serialized segment proofs (from all workers) into the final STARK.
    Aggregate,
RS
run edit_replace "$RBLIB" "$TMP/e6c_old.txt" "$TMP/e6c_new.txt" "ProveSegments,"
printf '%s' '            Self::ProveStark => write!(f, "prove_stark"),' > "$TMP/e6d_old.txt"
cat > "$TMP/e6d_new.txt" <<'RS'
            Self::ProveStark => write!(f, "prove_stark"),
            Self::ProveSegments => write!(f, "prove_segments"),
            Self::Aggregate => write!(f, "aggregate"),
RS
run edit_replace "$RBLIB" "$TMP/e6d_old.txt" "$TMP/e6d_new.txt" 'f, "prove_segments"'
printf '%s' '    pub num_gpus: usize,' > "$TMP/e6e_old.txt"
cat > "$TMP/e6e_new.txt" <<'RS'
    pub num_gpus: usize,

    /// [multi-gpu ①] this worker's id in 0..num_workers (mode=prove-segments).
    #[arg(long, default_value_t = 0)]
    pub worker_id: usize,
    /// [multi-gpu ①] total workers = GPUs (mode=prove-segments / aggregate).
    #[arg(long, default_value_t = 1)]
    pub num_workers: usize,
    /// [multi-gpu ①] dir for serialized segment proofs (prove-segments writes, aggregate reads).
    #[arg(long)]
    pub segments_out: Option<PathBuf>,
RS
run edit_replace "$RBLIB" "$TMP/e6e_old.txt" "$TMP/e6e_new.txt" "pub worker_id: usize"
printf '%s' '                    BenchMode::GenerateFixtures => {' > "$TMP/e6f_old.txt"
cat > "$TMP/e6f_new.txt" <<'RS'
                    BenchMode::ProveSegments => {
                        let dir = args
                            .segments_out
                            .clone()
                            .expect("--segments-out required for prove-segments");
                        std::fs::create_dir_all(&dir)?;
                        let nw = args.num_workers.max(1);
                        let prover = sdk.async_app_prover(elf, nw)?;
                        let (segs, user_pv) = prover.prove_shard(stdin, args.worker_id, nw)?;
                        for (idx, proof) in &segs {
                            write_object_to_file(dir.join(format!("seg-{idx}.bitcode")), proof)?;
                        }
                        if let Some(pv) = user_pv {
                            write_object_to_file(dir.join("user-pv.bitcode"), &pv)?;
                        }
                        println!(
                            "worker {}/{} wrote {} segment proofs to {}",
                            args.worker_id, nw, segs.len(), dir.display()
                        );
                    }
                    BenchMode::Aggregate => {
                        let dir = args
                            .segments_out
                            .clone()
                            .expect("--segments-out required for aggregate");
                        let mut entries: Vec<(usize, std::path::PathBuf)> = std::fs::read_dir(&dir)?
                            .filter_map(|e| e.ok().map(|e| e.path()))
                            .filter_map(|p| {
                                let n = p.file_name()?.to_str()?.to_string();
                                let idx = n
                                    .strip_prefix("seg-")?
                                    .strip_suffix(".bitcode")?
                                    .parse::<usize>()
                                    .ok()?;
                                Some((idx, p))
                            })
                            .collect();
                        entries.sort_by_key(|(i, _)| *i);
                        println!("aggregating {} segment proofs from {}", entries.len(), dir.display());
                        let app_proof: ContinuationVmProof<SC> = ContinuationVmProof {
                            per_segment: entries
                                .iter()
                                .map(|(_, p)| read_object_from_file(p))
                                .collect::<eyre::Result<Vec<_>>>()?,
                            user_public_values: read_object_from_file(dir.join("user-pv.bitcode"))?,
                        };
                        let mut stark = sdk.prover(elf)?.with_program_name(program_name);
                        let leaf = stark.agg_prover.generate_leaf_proofs(&app_proof)?;
                        let proof = stark
                            .agg_prover
                            .aggregate_leaf_proofs(leaf, app_proof.user_public_values.public_values)?;
                        let block_hash = proof
                            .user_public_values
                            .iter()
                            .map(|pv| pv.as_canonical_u32() as u8)
                            .collect::<Vec<u8>>();
                        println!("block_hash (aggregate): {}", ToHexExt::encode_hex(&block_hash));
                        if let Some(output_dir) = args.output_dir.as_ref() {
                            let versioned_proof = VersionedVmStarkProof::new(proof)?;
                            let json = serde_json::to_vec_pretty(&versioned_proof)?;
                            fs::write(output_dir.join("proof.json"), json)?;
                            println!("wrote proof json to {}", output_dir.display());
                        }
                    }
                    BenchMode::GenerateFixtures => {
RS
# marker must be UNIQUE to the ARM (not the enum doc-comment that Edit 6c added, which also contains
# "Prove only THIS worker") — else 6f SKIPs and the match arm is never inserted -> runtime unreachable!().
run edit_replace "$RBLIB" "$TMP/e6f_old.txt" "$TMP/e6f_new.txt" 'required for prove-segments'

# ── workspace exclude: stop cargo from claiming .vendor/* as openvm-eth members ─
# Without this, the vendored crates' `authors.workspace = true` (and other inherited
# fields) resolve against openvm-eth's [workspace.package] (which lacks them) -> error.
echo "== workspace exclude .vendor =="
printf '%s' 'exclude = []' > "$TMP/wex_old.txt"
printf '%s' 'exclude = [".vendor"]' > "$TMP/wex_new.txt"
run edit_replace "$ETH/Cargo.toml" "$TMP/wex_old.txt" "$TMP/wex_new.txt" 'exclude = [".vendor"]'

# ── cargo [patch] — auto-discovered from Cargo.lock + vendored crate dirs ─────
echo "== cargo [patch] overrides =="
if grep -q 'BEGIN openvm-infra multi-gpu patch' "$ETH/Cargo.toml" 2>/dev/null; then
  echo "  SKIP (patch section already present)"
else
  py "$LOCK" "$VENDOR" >> "$TMP/patch.toml" <<'PY'
import sys, re, os, subprocess
lock, vendor = sys.argv[1], sys.argv[2]
txt = open(lock, encoding='utf-8').read()
# package blocks: name + source
blocks = re.findall(r'\[\[package\]\]\nname = "([^"]+)"\nversion = "[^"]+"\nsource = "([^"]+)"', txt)
def crate_dir(repo_root, name):
    # find the crate dir whose Cargo.toml declares `name = "<name>"`
    try:
        out = subprocess.run(["grep","-rlE",f'^name = "{re.escape(name)}"',"--include=Cargo.toml",repo_root],
                             capture_output=True, text=True).stdout.strip().splitlines()
    except Exception:
        out = []
    return os.path.dirname(out[0]) if out else None
sources = {
  "https://github.com/openvm-org/openvm.git":        (f"{vendor}/openvm",        []),
  "https://github.com/openvm-org/stark-backend.git": (f"{vendor}/stark-backend", []),
}
seen=set()
for name, src in blocks:
    for url,(root,acc) in sources.items():
        if url in src and name not in seen:
            seen.add(name)
            d = crate_dir(root, name)
            if d: acc.append((name, os.path.relpath(d, os.path.dirname(lock))))
            else: print(f"# WARN: crate dir for {name} not found under {root}", file=sys.stderr)
print("# BEGIN openvm-infra multi-gpu patch (auto-generated)")
for url,(root,acc) in sources.items():
    if not acc: continue
    print(f'[patch."{url}"]')
    for name,rel in sorted(acc):
        print(f'{name} = {{ path = "{rel}" }}')
print("# END openvm-infra multi-gpu patch")
PY
  if [[ -s "$TMP/patch.toml" ]]; then
    printf '\n' >> "$ETH/Cargo.toml"; cat "$TMP/patch.toml" >> "$ETH/Cargo.toml"
    echo "  OK: appended [patch] for $(grep -c '= { path' "$TMP/patch.toml") crates"
  else
    echo "  FAIL: produced no [patch] entries (inspect Cargo.lock format)"; FAILED=1
  fi
fi

# ── keep the committed Cargo.lock (minimal-churn build) ──────────────────────
# CRITICAL: a full re-resolve ("Locking … to latest compatible") bumps transitive deps
# like winnow 0.7 -> 1.0, which breaks alloy-dyn-abi 1.5.x (142 errors). Restoring the
# committed lock means the first `cargo build` only ADDS the vendored crates (same versions
# openvm-eth already pinned) and keeps everything else put.
if git -C "$ETH" rev-parse --git-dir >/dev/null 2>&1; then
  git -C "$ETH" checkout -- Cargo.lock 2>/dev/null && echo "restored committed Cargo.lock (avoids winnow/alloy re-resolve)"
fi

echo ""
echo "== summary =="
echo "vendored: $VENDOR/openvm @ $OPENVM_REV ; $VENDOR/stark-backend @ $STARK_REV"
if [[ "$FAILED" == 0 ]]; then
  echo "ALL EDITS APPLIED. Next (FREE, no GPU): cd $ETH && cargo build --release --bin openvm-reth-benchmark"
  echo "Then on the box: cargo build --release --bin openvm-reth-benchmark --features cuda"
else
  echo ">>> SOME EDITS FAILED (rev drift). Hand-apply the FAILed ones from ../docs/openvm-multigpu.md, then re-run."
  exit 1
fi
